### PR TITLE
Setup tests

### PR DESCRIPTION
**Pull request by e553y**
- add jest.config.js to set testing environment to 'node'
 - use proxyquire for mocking intenally 'requied' config.js file
 - use a 'test' database to avoid polluting actual database

@ngodavidhuy @Collin-St @worrierx0 
Please checkout this PR

### CODE REVIEW

**Comment by e553y** [comment]
[[4]write test for server code](https://trello.com/c/jjmg7Icz/30-4write-test-for-server-code)

**Comment by ngodavidhuy** [comment]
Merge conflicts?

**Comment by e553y** [comment]
@ngodavidhuy I rebased this banch. This should have no confilicts now.

**Comment by ngodavidhuy** [comment]
This looks great, Esey! Keep it up!

**Pull request merged**
